name: Testing container bug
on:
  workflow_dispatch:
jobs:
  unit-tests:
    
    runs-on: ubuntu-latest

    container: openjdk:17-jdk-alpine

    steps:
      - name: Setup git
        working-directory: ""
        run: |
          apk add -q --no-cache --no-progress git yq tar
          git config --global --add safe.directory $GITHUB_WORKSPACE
          apk add maven
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Cache maven packages
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: test_1

      - if: steps.cache.outputs.cache-hit != 'true'
        name: Run liquibase update
        run: |
          mvn install
          pwd
